### ISSUE TITLE
Usage procedure

### ISSUE THREAD

**Issue by xguerin** [powerman/wcwidth-icons#2]
Hey there,

Is there any particular procedure to follow? I tried this on OpenBSD 6.2 with patched vim8, but I did not see any difference.

At least, in vim it seems that the icon is considered of width 2, but the pictogram is still truncated.

**Comment by powerman** [comment]
You need right font, right terminal, and only then patched vim. (Also, screenshots usually help debugging such issue, together with details about used font/terminal.) So, first check is you've correct double-width icons in terminal.

**Comment by xguerin** [comment]
I use PragmataPro with all the nerd font extensions (devicons, powerline, etc..). I have a whole bunch of nerd fonts installed that I can try with as well. I'll upload some screenshot later today.
