### ISSUE TITLE
urxvt not rendering unicode but gvim does

### ISSUE THREAD

**Issue by malikbenkirane** [powerman/wcwidth-icons#3]
Hello,

I just get on your project while trying to fix urxvt not displaying unicode characters with *termsyn* (from sourceforge [here](https://sourceforge.net/projects/termsyn/))   but a part from the fact that the solution you developped is very interesting i have problems solving my issue.

To illustrate the issue i am facing with urxvt here is a screenshot I took (not rendering the unicode character)

![urxvt screenshot](https://i.imgur.com/of1J6jO.png)
The Xresources config I use to load the font is
```
URxvt.font: xft:Termsyn:size=7
```
I have
```
LD_PRELOAD=/usr/lib/libwcwidth-icons.so
```
in the environment from which I am executing urxvt and when I check dynamic linking with ldd it seems linked
```
...
/usr/lib/libwcwidth-icons.so (0x00007fcbff44b000)
...
```

Finally here is what I get within gvim (my clock unicode character is rendered here)

![gvim screenshot](https://i.imgur.com/N44Pqj1.png)

Thanks a lot.

**Comment by malikbenkirane** [comment]
the issue remains using
```
URxvt.font: xft:termsyn:size=7,xft:FreeSans:size=7
```
for example for Xresources (while FreeSans provides Unicode characters)

**Comment by powerman** [comment]
There are a lot of other things which may be setup in wrong way, so I can't give you concrete hints. All I can recommend is step back and try to setup it from the beginning, one thing at a time, testing after each step. First - try to get one of Nerd Fonts to work (they've good install instructions and wiki, plus we know these fonts work for sure), for usual (non-wide) unicode symbols. Next - try to get wide symbols to work, both in urxvt and vim. Then try to switch to your Termsyn font.

Here are examples from my own setup, which worked some time ago (I believe you have to set `boldFont` in any case, but `URxvt*` should work the same as `URxvt.`):
```
URxvt*font:             xft:DroidSansMono Nerd Font:style=Book:size=20
URxvt*boldFont:         xft:DroidSansMono Nerd Font:style=Book:size=20

URxvt*font:             xft:RobotoMono Nerd Font:style=Medium:size=20
URxvt*boldFont:         xft:RobotoMono Nerd Font:style=Medium:size=20
URxvt*italicFont:       xft:RobotoMono Nerd Font:style=Medium Italic:size=20
URxvt*boldItalicFont:   xft:RobotoMono Nerd Font:style=Medium Italic:size=20

URxvt*font:             xft:CodeNewRoman Nerd Font:style=Book:size=21
URxvt*boldFont:         xft:CodeNewRoman Nerd Font:style=Book:size=21
URxvt*italicFont:       xft:CodeNewRoman Nerd Font:style=Italic:size=21
URxvt*boldItalicFont:   xft:CodeNewRoman Nerd Font:style=Italic:size=21
```
and this one I'm using right now (probably Iosevka font was downloaded separately, it's not one of Nerd Fonts):
```
URxvt*font:             xft:D2CodingForPowerline Nerd Font:style=Regular:size=24,xft:Iosevka Term Slab
URxvt*boldFont:         xft:D2CodingBoldForPowerline Nerd Font:style=Bold:size=24,xft:Iosevka Term Slab
```
Also - don't use just one symbol while testing, instead output (cat/vim) text file with a lot of them, for example from these files: https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/lib

**Comment by powerman** [comment]
And do not forget to reset after each change, using commands like `fc-cache -fv ~/.local/share/fonts` (if you've installed fonts there) and `xrdb ~/.Xresources` and starting new urxvt process.

**Comment by malikbenkirane** [comment]
I'v tried with the fonts you proposed but I am embarassed because it stills not render unicode
![hint](https://i.imgur.com/CAcWS7d.png)
But you might help me through this because I just noticed this weird message from urxvt trying to load Courier New and that does'nt make any sense to me.

[Here is the full Xresources.conf](https://gist.github.com/malikbenkirane/64110eb9d1501d5e89bf299e07f87fff)

**Comment by powerman** [comment]
At a glance it looks like urxvt font wasn't set. Check output of this command to make sure you've actually set required resource:
```sh
$ xrdb -query | grep URxvt.font
URxvt*font:	xft:D2CodingForPowerline Nerd Font:style=Regular:size=24,xft:Iosevka Term Slab
```

**Comment by malikbenkirane** [comment]
For the use case I gave you here is the output of `xrdb -query`
```
URxvt*font:	xft:CodeNewRoman Nerd Font:style=Book:size=9
```
But still is I have positive results with Nerdfonts with the scripts you refeered to

![mitig](https://i.imgur.com/pvD5UNn.png)

**Comment by malikbenkirane** [comment]
Although I still confused, I think I finally made somehing okay combining the fonts. Thanks for the support !
![screenshot](https://i.imgur.com/UrE7FFb.png)

**Comment by powerman** [comment]
Okay, so nerd font is loaded and wide symbols works. Now you can try to change font - keep in mind it may be not compatible with wide symbols (as you've seen it's possible to compile nerd fonts in both ways - with/without wide chars) or your clock symbol may have another codepoint in that font - you can use tools like fontforge to view all available codepoints in a font.

As for font error - there are many places which may try to load this font, from fontconfig setup in /etc/fonts/ and your home dir to urxvt plugins… just in case, check also `xrdb -query | grep -i Courier` output - maybe some other resource refer to it.
